# Generate a random matrix

In [1]:
import numpy as np

In [2]:
rmat = np.zeros((5, 5))
rmat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
for i in range(len(rmat)):
    for j in range(len(rmat[i])):
        rmat[i][j] = np.random.uniform(-1.0, 1.0)
rmat

array([[ 0.38237273, -0.28098603,  0.12140554,  0.79304058,  0.6345158 ],
       [ 0.91358735,  0.93415311,  0.18354814,  0.77679791,  0.35631391],
       [ 0.73573231,  0.93016902, -0.26026428,  0.54911047,  0.70442983],
       [-0.67082626,  0.59892616,  0.68323872, -0.46333925,  0.20810979],
       [-0.63060655, -0.59341754,  0.86304413, -0.29471893, -0.99859682]])

symmetrization
<br>
$H_{s} = (H +H^{T} )/2$

In [4]:
rmatT = np.transpose(rmat)
rmatT

array([[ 0.38237273,  0.91358735,  0.73573231, -0.67082626, -0.63060655],
       [-0.28098603,  0.93415311,  0.93016902,  0.59892616, -0.59341754],
       [ 0.12140554,  0.18354814, -0.26026428,  0.68323872,  0.86304413],
       [ 0.79304058,  0.77679791,  0.54911047, -0.46333925, -0.29471893],
       [ 0.6345158 ,  0.35631391,  0.70442983,  0.20810979, -0.99859682]])

In [5]:
RMTs = (rmat + rmatT)/2
RMTs

array([[ 0.38237273,  0.31630066,  0.42856892,  0.06110716,  0.00195462],
       [ 0.31630066,  0.93415311,  0.55685858,  0.68786203, -0.11855182],
       [ 0.42856892,  0.55685858, -0.26026428,  0.6161746 ,  0.78373698],
       [ 0.06110716,  0.68786203,  0.6161746 , -0.46333925, -0.04330457],
       [ 0.00195462, -0.11855182,  0.78373698, -0.04330457, -0.99859682]])

In [6]:
grmt = np.zeros((5, 5))
grmt

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
for i in range(len(grmt)):
    for j in range(i, len(grmt[i])):
        grmt[i][j] = np.random.normal(0.0, 1.0)
        grmt[j][i] = grmt[i][j]
grmt  

array([[ 0.30080138,  0.37083016, -1.33442313, -0.14477761, -1.91078429],
       [ 0.37083016, -0.03323607,  3.3272438 , -0.66776093, -0.33969376],
       [-1.33442313,  3.3272438 , -0.70546326, -1.06323783,  0.16370404],
       [-0.14477761, -0.66776093, -1.06323783,  0.52165121, -0.69929786],
       [-1.91078429, -0.33969376,  0.16370404, -0.69929786,  0.15263751]])

Spectral analysis of the matrix

In [8]:
from numpy import linalg as LA

In [9]:
w, v = LA.eig(grmt)
print(w)

[-4.12547656  3.66604989  2.20406946 -1.79495797  0.28670594]


In [10]:
print(v)

[[ 0.30720718 -0.28322388  0.64288324  0.5514466   0.32865752]
 [-0.59756993  0.5874127   0.38996651  0.31153391 -0.22074701]
 [ 0.72929656  0.63092967  0.12096287 -0.09484126 -0.21547019]
 [ 0.10238973 -0.36956833 -0.01727188  0.29481058 -0.87505657]
 [ 0.07859257  0.2001938  -0.6478402   0.70918625  0.1763621 ]]


In [11]:
np.sum(w)

0.23639075752658933