Generating a random matrix

In [1]:
import numpy as np

In [2]:
rmat = np.zeros((5, 5))
rmat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
for i in range(len(rmat)):
    for j in range(len(rmat[i])):
        rmat[i][j] = np.random.uniform(-1.0, 1.0)
rmat

array([[-0.3310685 , -0.76399741, -0.90861661,  0.17075419, -0.87669729],
       [ 0.41303624, -0.77920111, -0.69660287, -0.85661385, -0.81114316],
       [-0.84217042,  0.02607063,  0.14362259,  0.30310805, -0.17921563],
       [-0.96423744,  0.97197055, -0.20964329,  0.41377644, -0.76564859],
       [-0.22427753,  0.40563766,  0.47039379, -0.58112073, -0.83139593]])

symmetrization
<br>
$H_{s} = (H +H^{T} )/2$

In [5]:
rmatT = np.transpose(rmat)
rmatT

array([[-0.3310685 ,  0.41303624, -0.84217042, -0.96423744, -0.22427753],
       [-0.76399741, -0.77920111,  0.02607063,  0.97197055,  0.40563766],
       [-0.90861661, -0.69660287,  0.14362259, -0.20964329,  0.47039379],
       [ 0.17075419, -0.85661385,  0.30310805,  0.41377644, -0.58112073],
       [-0.87669729, -0.81114316, -0.17921563, -0.76564859, -0.83139593]])

In [6]:
RMTs = (rmat + rmatT)/2
RMTs

array([[-0.3310685 , -0.17548058, -0.87539351, -0.39674162, -0.55048741],
       [-0.17548058, -0.77920111, -0.33526612,  0.05767835, -0.20275275],
       [-0.87539351, -0.33526612,  0.14362259,  0.04673238,  0.14558908],
       [-0.39674162,  0.05767835,  0.04673238,  0.41377644, -0.67338466],
       [-0.55048741, -0.20275275,  0.14558908, -0.67338466, -0.83139593]])

In [19]:
grmt = np.zeros((5, 5))
grmt

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
for i in range(len(grmt)):
    for j in range(i, len(grmt[i])):
        grmt[i][j] = np.random.normal(0.0, 1.0)
        grmt[j][i] = grmt[i][j]
grmt  

array([[-0.93903056, -1.76539175, -0.16336106, -1.41224004, -0.54211977],
       [-1.76539175, -0.54713798, -1.67056795, -1.13768674,  0.14454736],
       [-0.16336106, -1.67056795,  1.50474573,  0.60059583,  0.50734047],
       [-1.41224004, -1.13768674,  0.60059583,  0.15217065,  0.44480571],
       [-0.54211977,  0.14454736,  0.50734047,  0.44480571, -0.66741868]])

Spectral analysis of the matrix

In [9]:
from numpy import linalg as LA

In [21]:
w, v = LA.eig(grmt)
print(w)

[-3.58309047  2.95677381  1.37285973 -1.05899026 -0.18422365]


In [17]:
print(v)

[[ 0.35964442  0.64175074  0.66480322  0.12556223  0.0329042 ]
 [ 0.27213994  0.56080639 -0.63197047 -0.1897885  -0.41955893]
 [-0.55736805  0.03529876  0.31512998 -0.05182734 -0.7655729 ]
 [ 0.60301857 -0.45702385  0.22867862 -0.51535693 -0.33107571]
 [-0.3497216   0.25206225  0.08395943 -0.82458208  0.35661551]]


In [22]:
np.sum(w)

-0.4966708386196148